### ISSUE TITLE
AdConfigsResponseParser Error

### ISSUE THREAD

**Issue by cthomaschase** [picatcha/adsnative-sdk-ios#1]
We're getting

``-[__NSCFString containsString:]: unrecognized selector sent to instance``

The complete trace is here

Thread : Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x186ff709c __exceptionPreprocess
1  libobjc.A.dylib                0x192f75d78 objc_exception_throw
2  CoreFoundation                 0x186ffbd14 __methodDescriptionForSelector
3  CoreFoundation                 0x186ff9a7c ___forwarding___
4  CoreFoundation                 0x186f194ac _CF_forwarding_prep_0
5  AftyChat                       0x1006d8490 -[AdConfigsResponseParser adConfigsSetForData:error:] (AdConfigsResponseParser.m:238)
6  AftyChat                       0x1006eb53c -[AdServerPinger connectionDidFinishLoading:] (AdServerPinger.m:112)
7  Foundation                     0x187aa6bb4 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke
8  Foundation                     0x187aa6aa0 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]
9  Foundation                     0x187aa6998 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:]
10 CFNetwork                      0x186bddd4c ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke
11 CFNetwork                      0x186bdc348 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2
12 CFNetwork                      0x186c1e0e4 ___ZNK17CoreSchedulingSet13_performAsyncEPKcU13block_pointerFvvE_block_invoke
13 CoreFoundation                 0x186ef54f8 CFArrayApplyFunction
14 CFNetwork                      0x186b51f14 RunloopBlockContext::perform()
15 CFNetwork                      0x186b51da8 MultiplexerSource::perform()
16 CFNetwork                      0x186b51be4 MultiplexerSource::_perform(void*)
17 CoreFoundation                 0x186fb777c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
18 CoreFoundation                 0x186fb6ad8 __CFRunLoopDoSources0
19 CoreFoundation                 0x186fb4d70 __CFRunLoopRun
20 CoreFoundation                 0x186ef5b38 CFRunLoopRunSpecific
21 GraphicsServices               0x18c91b830 GSEventRunModal
22 UIKit                          0x189f340e8 UIApplicationMain
23 AftyChat                       0x100092e8c main (main.m:16)
24 libdyld.dylib                  0x19355faa0 start

**Comment by ArvindBharadwaj92** [comment]
This issue has been fixed.
