### ISSUE TITLE
Issue when integrating with Xcode 8

### ISSUE THREAD

**Issue by rafaelks** [picatcha/adsnative-sdk-ios#4]
Hello!

**What I did:**
- Downloaded latest SDK from AdsNative documentation;
- Added it to the project
- Tried to build the project

I'm trying to integrate the SDK in our project, but I'm having a few issues:

```
duplicate symbol _OBJC_CLASS_$_Reachability in:
    /Users/rafaelks/Library/Developer/Xcode/DerivedData/WeHeartIt-cootrvudelinqfagbssshjlihbfs/Build/Products/Debug-iphonesimulator/Reachability/libReachability.a(Reachability.o)
    /Users/rafaelks/Projects/WHI/WeHeartIt/Ads/AdsNative/SDK/AdsNativeSDK.framework/AdsNativeSDK(Reachability.o)
duplicate symbol _OBJC_METACLASS_$_Reachability in:
    /Users/rafaelks/Library/Developer/Xcode/DerivedData/WeHeartIt-cootrvudelinqfagbssshjlihbfs/Build/Products/Debug-iphonesimulator/Reachability/libReachability.a(Reachability.o)
    /Users/rafaelks/Projects/WHI/WeHeartIt/Ads/AdsNative/SDK/AdsNativeSDK.framework/AdsNativeSDK(Reachability.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Also, I'm seeing lots of warnings:

![screen shot 2016-09-15 at 16 52 05](https://cloud.githubusercontent.com/assets/551004/18565079/c420cc72-7b64-11e6-8f60-a6f44130c911.png)

Am I doing something wrong, or missing some step?

Thank you!

**Comment by ArvindBharadwaj92** [comment]
Hi @rafaelks 
Do you have `Reachability.h` and `Reachability.m` files in your app? Looks like that might be clashing with the SDK. The SDK internally has the same class name being used. 

As for the warnings you're seeing, could you open the AdsNativeSDK.framework file manually in the finder and check if those headers are present in the `Headers` folder? If they are, maybe try cleaning xcode and rebuilding.

**Comment by rafaelks** [comment]
@ArvindBharadwaj92 Yes, I do have the `Reachability` files (via [Pods](https://github.com/tonymillion/Reachability)). I've a few ideas:

1.  I could fork Reachability project and rename classes to something else;
2. AdsNative could rename classes inside framework to make sure no one else will have this problem again;

What do you suggest?

**Comment by ArvindBharadwaj92** [comment]
@rafaelks we'll be releasing an updated SDK soon to include xcode 8 and iOS 10 support. I'll be making the change for Reachability along with that. For now, to unblock yourself, perhaps you could fork the Reachability project and rename the class temporarily. Sound good?

**Comment by rafaelks** [comment]
@ArvindBharadwaj92 Yeah, sounds good! Thank you.
